### PR TITLE
Replace chromeOptions by browsersOptions

### PR DESCRIPTION
**Pull request by karolchmist**
chromeOptions work fine but it's a bit specific to be passed around. If a new option is to be added one day, it would require adding yet another parameter everywhere. 

I propose to replace chromeOptions with browsersOptions.

This is just a quick proposition. If you like the change, I can make update Readme etc.,

### CODE REVIEW

**Comment by karolchmist** [comment]
BTW, I don't know typescript and I didn't test it, but it compiles...

**Comment by t2ym** [comment]
@karolchmist Thanks for the PR.  I am going to release a version with your changes plus more extensions since I found an issue on the changes and I noticed that Firefox 55 on Linux supports `--headless` options as well.

If `browsersOptions` is not set, the change will throw null object reference exception on getting properties for browsers.

**Comment by t2ym** [comment]
@karolchmist I released 2.2.0 with your PR and headless Firefox support. The PR has been merged in my local workspace and thus is not shown on the merging network in the GitHub page.

Only the Linux version of Firefox 55 supports headless mode.

**Comment by karolchmist** [comment]
This is perfect, thank you! 

We were hoping to run WCT under Firefox, so the new version is very helpful.

**Pull request merged**
